import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CookieConsent from "../components/CookieConsent";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ebook Library App',
  description: 'Generated by Ebook-library-application',
  icons: {
    icon: "/images/logo.svg", 
    shortcut: "/images/logo.svg", 
    apple: "/images/logo.svg", 
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <CookieConsent />
      </body>
    </html>
  )
}